export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const SET_ORDERS_START = 'SET_ORDERS_START';
export const SET_ORDERS_SUCCESS = 'SET_ORDERS_SUCCESS';
export const SET_ORDERS_FAIL = 'SET_ORDERS_FAIL';